# Numpy Crash Course

## Import Numpy Library

In [1]:
import numpy as np

## Creating 1D Numpy Arrays

In [2]:
numbers = [1, 2, 3, 4, 5]
print(numbers)
print(type(numbers))

[1, 2, 3, 4, 5]
<class 'list'>


In [3]:
numbers_np = np.array(numbers)
print(numbers_np)
print(type(numbers_np))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
numbers_np.dtype

dtype('int32')

## Creating 2D Numpy Arrays

In [5]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(matrix)
print(type(matrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [6]:
matrix_np = np.array(matrix)
print(matrix_np)
print(type(matrix_np))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


## Numpy Built-in Methods

### Array creation routines

https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html


In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [98]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Creating Numpy Array with Random Numbers

In [23]:
np.random.rand(3)

array([2.41710585e-04, 8.51528726e-01, 2.47222849e-01])

In [24]:
np.random.randn(3)

array([ 0.48944936, -1.58142495,  1.62167047])

In [25]:
np.random.randint(1, 100)

13

In [26]:
np.random.randint(1, 100, 10)

array([53, 91, 14, 52, 62, 60, 53, 75, 52, 90])

### Max - Min

|  Number  | 92 | 52 | 78 | 95 | 27 | 79 | 69 | 72 | 59 | 51 | 48 | 59 | 77 | 11 | 23 | 91 | 57 | 97 | 46 | 29 |
|:--------:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|----|----|----|----|----|----|----|----|
|  INDEX   |  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 |

In [27]:
data = np.array([92, 52, 78, 95, 27, 79, 69, 72, 59, 51, 48, 59, 77, 11, 23, 91, 57, 97, 46, 29])

In [28]:
data.max()

97

In [29]:
data.argmax()

17

In [30]:
data.min()

11

In [31]:
data.argmin()

13

### Reshape

In [32]:
data.shape

(20,)

In [33]:
data_20_rows = data.reshape(20, 1)
print(data_20_rows)
print(data_20_rows.shape)

[[92]
 [52]
 [78]
 [95]
 [27]
 [79]
 [69]
 [72]
 [59]
 [51]
 [48]
 [59]
 [77]
 [11]
 [23]
 [91]
 [57]
 [97]
 [46]
 [29]]
(20, 1)


In [37]:
number = np.arange(25)
print(number)
square_matrix = number.reshape(5, 5)
print(square_matrix)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Indexing Slicing and Broadcasting

### 1D Numpy Array Indexing

| Number | 1   | 2  | 3  | 4  | 5  | 6  | 7  | 8  | 9  | 10 |
|--------|-----|----|----|----|----|----|----|----|----|----|
| Index  | 0   | 1  | 2  | 3  | 4  | 5  | 6  | 7  | 8  | 9  |
| Index  | -10 | -9 | -8 | -7 | -6 | -5 | -4 | -3 | -2 | -1 |

In [44]:
numbers = np.arange(1, 11)
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [40]:
numbers[7]

8

In [41]:
numbers[-1]

10

In [42]:
numbers[-5]

6

### 1D Numpy Array Slicing

In [45]:
numbers[:5]

array([1, 2, 3, 4, 5])

In [46]:
numbers[5:]

array([ 6,  7,  8,  9, 10])

In [47]:
numbers[2:4]

array([3, 4])

In [48]:
numbers[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
numbers[1:9:2]

array([2, 4, 6, 8])

### 1D Numpy Array Broadcasting

In [50]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
zeros[1:5] = 100
print(zeros)

[  0. 100. 100. 100. 100.   0.   0.   0.   0.   0.]


In [52]:
zeros[:] = 200
print(zeros)

[200. 200. 200. 200. 200. 200. 200. 200. 200. 200.]


### 2D Numpy Array Indexing

|   | 0  | 1  | 2  | 3  |
|---|----|----|----|----|
| 0 |  1 |  2 |  3 |  4 |
| 1 |  5 |  6 |  7 |  8 |
| 2 |  9 | 10 | 11 | 12 |
| 3 | 13 | 14 | 15 | 16 |

In [53]:
matrix = np.arange(1, 17).reshape(4,4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [54]:
matrix[1]

array([5, 6, 7, 8])

In [55]:
matrix[2][3]

12

In [56]:
matrix[2,3]

12

In [57]:
matrix[-1][-1]

16

### 2D Numpy Array Slicing

In [58]:
matrix[[1,2,3]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
matrix[[1,2,3],[3]]

array([ 8, 12, 16])

In [60]:
matrix[:3,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [61]:
matrix[:3,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
matrix[1:4,2:3]

array([[ 7],
       [11],
       [15]])

### 2D Numpy Array Broadcasting

In [63]:
zeros_matrix = np.zeros((4,4))
zeros_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
zeros_matrix[:2,:2] = 1
zeros_matrix

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Copy Numpy Array

In [65]:
array_1 = np.ones(10)
print('Array_1: ',array_1)
array_2 = array_1
print('Array_2: ',array_2)
array_2[:5] = 10
print('Array_2: ',array_2)
print('Array_1: ',array_1)

Array_1:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array_2:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array_2:  [10. 10. 10. 10. 10.  1.  1.  1.  1.  1.]
Array_1:  [10. 10. 10. 10. 10.  1.  1.  1.  1.  1.]


In [66]:
array_1 = np.ones(10)
print('Array_1: ',array_1)
array_2 = array_1.copy()
print('Array_2: ',array_2)
array_2[:5] = 10
print('Array_2: ',array_2)
print('Array_1: ',array_1)

Array_1:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array_2:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array_2:  [10. 10. 10. 10. 10.  1.  1.  1.  1.  1.]
Array_1:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Selection

In [67]:
number = np.arange(0, 10)
number

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
number < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [69]:
number[[True,  True,  True,  True,  True, False, False, False, False, False]]

array([0, 1, 2, 3, 4])

In [70]:
number[number < 5]

array([0, 1, 2, 3, 4])

## Numpy Array Operations

In [71]:
array_1 = np.arange(1, 11)
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
array_2 = np.ones(10)
array_2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [73]:
array_1 + array_2

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [74]:
array_1 - array_2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [75]:
array_1 * array_1

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
array_1 / array_1

In [76]:
array_1 + 2 

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
array_1 - 2 

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [78]:
array_1 * 2 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [79]:
array_1 ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [80]:
np.sqrt(array_1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [81]:
np.exp(array_1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [82]:
np.log(array_1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

## Numpy VS List

In [83]:
import timeit

In [84]:
data_list = list(range(0, 50000000))
start = timeit.default_timer()

for i,member in enumerate(data_list):
    data_list[i] = data_list[i] ** 2

end = timeit.default_timer()
print('Computing Time: ',end - start, 's')

Computing Time:  21.41688850000014 s


In [85]:
array = np.arange(0, 50000000)
start = timeit.default_timer()

array = array ** 2

end = timeit.default_timer()
print('Computing Time: ',end - start, 's')

Computing Time:  0.13110799999981282 s


In [87]:
data_list = list(range(0, 50000000))
start = timeit.default_timer()

map(lambda x: x**2 ,data_list)

end = timeit.default_timer()
print('Computing Time: ',end - start, 's')

Computing Time:  9.62000001436536e-05 s


### Execercise: Write the program to calculate a dot product of two vectors.
    1. Using list.
    2. Using Numpy Array.
    

In [95]:
array1 = [1,2,3]
array2 = [3,4,5]
result = 0
for i in range(3):
    result += array1[i]*array2[i]
print(result)

26


In [92]:
array1 = np.array([1,2,3])
array2 = np.array([3,4,5])
result = (array1*array2).sum()
print(result)

26
