# Pandas Crash Course

## Import Pandas (and Numpy) Library

In [1]:
import pandas as pd
import numpy as np

## Creating Pandas Series from Python List

In [2]:
num_list = [2, 4, 6]

In [3]:
num_list_series = pd.Series(data=num_list)
print(num_list_series)
print(type(num_list_series))

0    2
1    4
2    6
dtype: int64
<class 'pandas.core.series.Series'>


In [4]:
labels = ['A', 'B', 'C']
num_list_series = pd.Series(data=num_list, index=labels)
print(num_list_series)
print(type(num_list_series))

A    2
B    4
C    6
dtype: int64
<class 'pandas.core.series.Series'>


## Creating Pandas Series from Numpy Array

In [5]:
array = np.array([2, 4, 6])

In [6]:
array_series = pd.Series(array)
print(array_series)
print(type(array_series))

0    2
1    4
2    6
dtype: int32
<class 'pandas.core.series.Series'>


In [7]:
labels = ['A', 'B', 'C']
array_series = pd.Series(array, labels)
print(array_series)
print(type(array_series))

A    2
B    4
C    6
dtype: int32
<class 'pandas.core.series.Series'>


## Mathematics Operation on Pandas Series

In [8]:
series1 = pd.Series([10, 40, 15, 30], index=['THB', 'EUR', 'JPY', 'AUS'])
print(series1)

THB    10
EUR    40
JPY    15
AUS    30
dtype: int64


In [9]:
series2 = pd.Series([14, 2, 5, 10], index=['THB', 'GBP', 'EUR', 'OMG'])
print(series2)

THB    14
GBP     2
EUR     5
OMG    10
dtype: int64


In [10]:
series3 = series1 + series2
print(series3)

AUS     NaN
EUR    45.0
GBP     NaN
JPY     NaN
OMG     NaN
THB    24.0
dtype: float64


## Creating DataFrame from Numpy Array

In [11]:
matrix = np.arange(1, 21).reshape(5,4)
print(matrix)
print(type(matrix))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
<class 'numpy.ndarray'>


In [12]:
df = pd.DataFrame(matrix, index=['A', 'B', 'C', 'D', 'E'], columns=['W', 'X', 'Y', 'Z'])
df

W   X   Y   Z
A   1   2   3   4
B   5   6   7   8
C   9  10  11  12
D  13  14  15  16
E  17  18  19  20

## Accessing Data in Pandas DataFrame

In [13]:
df['X']

A     2
B     6
C    10
D    14
E    18
Name: X, dtype: int32

In [14]:
print(type(df['X']))

<class 'pandas.core.series.Series'>


In [15]:
df[['W', 'Y']]

W   Y
A   1   3
B   5   7
C   9  11
D  13  15
E  17  19

In [16]:
print(type(df[['W', 'Y']]))

<class 'pandas.core.frame.DataFrame'>


## Mathematical Operation and Data Manipulation on Pandas DataFrame

### Adding Column to DataFrame

In [17]:
df['U'] = df['X'] + df['Y']

In [18]:
df

W   X   Y   Z   U
A   1   2   3   4   5
B   5   6   7   8  13
C   9  10  11  12  21
D  13  14  15  16  29
E  17  18  19  20  37

### Drop Column from Pandas DataFrame

In [19]:
df.drop('U', axis=1)

W   X   Y   Z
A   1   2   3   4
B   5   6   7   8
C   9  10  11  12
D  13  14  15  16
E  17  18  19  20

In [20]:
df

W   X   Y   Z   U
A   1   2   3   4   5
B   5   6   7   8  13
C   9  10  11  12  21
D  13  14  15  16  29
E  17  18  19  20  37

### Inplace Drop from Pandas DataFrame

In [21]:
df.drop('U', axis=1, inplace=True)

In [22]:
df

W   X   Y   Z
A   1   2   3   4
B   5   6   7   8
C   9  10  11  12
D  13  14  15  16
E  17  18  19  20

### Drop Row from Pandas DataFrame

In [23]:
df.drop('E', axis=0)

W   X   Y   Z
A   1   2   3   4
B   5   6   7   8
C   9  10  11  12
D  13  14  15  16

## Data Selection from Pandas DataFrame

### Selecting Data by Lable

In [24]:
df.loc['A']

W    1
X    2
Y    3
Z    4
Name: A, dtype: int32

In [25]:
df.loc['B', 'X']

6

In [26]:
df.loc[['A', 'B'], ['X', 'Y']]

X  Y
A  2  3
B  6  7

### Selecting Data by Index

In [27]:
df.iloc[1]

W    5
X    6
Y    7
Z    8
Name: B, dtype: int32

In [28]:
df.iloc[1, 3]

8

In [29]:
df.iloc[1:3, 0:2]

W   X
B  5   6
C  9  10

## Data Selection with Condition

In [30]:
df

W   X   Y   Z
A   1   2   3   4
B   5   6   7   8
C   9  10  11  12
D  13  14  15  16
E  17  18  19  20

### Create Boolean Condition

In [32]:
df>5

W      X      Y      Z
A  False  False  False  False
B  False   True   True   True
C   True   True   True   True
D   True   True   True   True
E   True   True   True   True

### Data Selection with Boolean Condition

In [33]:
df[df>5]

W     X     Y     Z
A   NaN   NaN   NaN   NaN
B   NaN   6.0   7.0   8.0
C   9.0  10.0  11.0  12.0
D  13.0  14.0  15.0  16.0
E  17.0  18.0  19.0  20.0

In [34]:
df[df['X']>6]

W   X   Y   Z
C   9  10  11  12
D  13  14  15  16
E  17  18  19  20

In [35]:
df[df['X']>9][['Y', 'X']]

Y   X
C  11  10
D  15  14
E  19  18

## Reindex Pandas DataFrame

### Reset Pandas DataFrame Index

In [36]:
df

W   X   Y   Z
A   1   2   3   4
B   5   6   7   8
C   9  10  11  12
D  13  14  15  16
E  17  18  19  20

In [37]:
df.reset_index()

index   W   X   Y   Z
0     A   1   2   3   4
1     B   5   6   7   8
2     C   9  10  11  12
3     D  13  14  15  16
4     E  17  18  19  20

## Reindex Pandas DataFrame

In [38]:
new_idx = ['THB', 'EUR', 'JPY', 'AUS', 'GBP']

In [39]:
df['Currency'] = new_idx

In [40]:
df

W   X   Y   Z Currency
A   1   2   3   4      THB
B   5   6   7   8      EUR
C   9  10  11  12      JPY
D  13  14  15  16      AUS
E  17  18  19  20      GBP

In [41]:
df.set_index('Currency')

W   X   Y   Z
Currency                
THB        1   2   3   4
EUR        5   6   7   8
JPY        9  10  11  12
AUS       13  14  15  16
GBP       17  18  19  20

In [42]:
df

W   X   Y   Z Currency
A   1   2   3   4      THB
B   5   6   7   8      EUR
C   9  10  11  12      JPY
D  13  14  15  16      AUS
E  17  18  19  20      GBP

In [43]:
df.set_index('Currency', inplace=True)

In [44]:
df

W   X   Y   Z
Currency                
THB        1   2   3   4
EUR        5   6   7   8
JPY        9  10  11  12
AUS       13  14  15  16
GBP       17  18  19  20

## Hierarcical Index (Multi-Index) Pandas DateFrame

### Creating Hierarcical Index from List

In [48]:
list_a = [1,2,3]
list_b = ['A','B','C']
list_c = list(zip(list_a,list_b))
print(list_c)
print(dict(list_c))

[(1, 'A'), (2, 'B'), (3, 'C')]
{1: 'A', 2: 'B', 3: 'C'}


In [45]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]

out_in = list(zip(outside,inside))
print(out_in)

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]


In [49]:
hier_index = pd.MultiIndex.from_tuples(out_in)
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           codes=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

### Creating Pandas Hierarcical Index DataFrame

In [50]:
df = pd.DataFrame(np.arange(1,13).reshape(6,2),index=hier_index,columns=['A','B'])
df

A   B
G1 1   1   2
   2   3   4
   3   5   6
G2 1   7   8
   2   9  10
   3  11  12

### Selecting Data from Pandas Hierarcical Index DataFrame

In [51]:
df.loc['G1']

A  B
1  1  2
2  3  4
3  5  6

In [52]:
df.loc['G1'].loc[1]

A    1
B    2
Name: 1, dtype: int32

### Creating Level Name for Pandas Hierarcical Index DataFrame

In [53]:
df.index.names

FrozenList([None, None])

In [54]:
df.index.names = ['Group','Num']

In [55]:
df

A   B
Group Num        
G1    1     1   2
      2     3   4
      3     5   6
G2    1     7   8
      2     9  10
      3    11  12

### Cross-Sectional Selecting Data from Pandas Hierarcical Index DataFrame

In [56]:
df.xs('G1')

A  B
Num      
1    1  2
2    3  4
3    5  6

In [57]:
df.xs(['G1',1])

A    1
B    2
Name: (G1, 1), dtype: int32

In [58]:
df.xs(1,level='Num')

A  B
Group      
G1     1  2
G2     7  8

## Handling Missing Data in Pandas DataFrame

In [59]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

### Drop Rows that Contain Missing Value

In [60]:
df.dropna()

A    B  C
0  1.0  5.0  1

### Drop Columns that Contain Missing Value

In [61]:
df.dropna(axis=1)

C
0  1
1  2
2  3

## Filling in Missing Value in Pandas DataFrame

### Filling with 0

In [62]:
df.fillna(value=0)

A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

### Filling with Mean Value

In [63]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

## Summarizing, Aggregating, and Grouping Data in Pandas DataFrame

In [64]:
data = {'Company': ['AAA', 'AAA', 'BBB', 'BBB', 'CCC', 'CCC'],
        'Person': ['Sam', 'Chris', 'Amy', 'Lily', 'Carl', 'Sarah'],
        'Sales': [200, 120, 340, 124, 243, 350]}
df = pd.DataFrame(data)
df

Company Person  Sales
0     AAA    Sam    200
1     AAA  Chris    120
2     BBB    Amy    340
3     BBB   Lily    124
4     CCC   Carl    243
5     CCC  Sarah    350

In [65]:
df.groupby('Company')

### Summarizing Data in Pandas DataFrame

In [66]:
df.groupby('Company').mean()

Sales
Company       
AAA      160.0
BBB      232.0
CCC      296.5

In [67]:
df.groupby('Company').mean()

Sales
Company       
AAA      160.0
BBB      232.0
CCC      296.5

In [68]:
df.groupby('Company').std()

Sales
Company            
AAA       56.568542
BBB      152.735065
CCC       75.660426

In [69]:
df.groupby('Company').min()

Person  Sales
Company              
AAA      Chris    120
BBB        Amy    124
CCC       Carl    243

In [70]:
df.groupby('Company').max()

Person  Sales
Company              
AAA        Sam    200
BBB       Lily    340
CCC      Sarah    350

In [71]:
df.groupby('Company').count()

Person  Sales
Company               
AAA           2      2
BBB           2      2
CCC           2      2

### Descriptive Statistic of Pandas DataFrame

In [72]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
AAA       2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
BBB       2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0
CCC       2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0

In [73]:
df.groupby('Company').describe().loc['AAA']

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: AAA, dtype: float64

## Concatenating, Merging, and Joining Pandas DataFrame

In [74]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'], 'B': ['B0', 'B1', 'B2']}, index=[0, 1, 2])
df1

A   B
0  A0  B0
1  A1  B1
2  A2  B2

In [76]:
df2 = pd.DataFrame({'A': ['A3', 'A4', 'A5'], 'B': ['B3', 'B4', 'B5']}, index=['A', 'B', 'C'])
df2

A   B
A  A3  B3
B  A4  B4
C  A5  B5

### Concatenating Pandas DataFrame

In [79]:
pd.concat([df1, df2])

A   B
0  A0  B0
1  A1  B1
2  A2  B2
A  A3  B3
B  A4  B4
C  A5  B5

In [80]:
pd.concat([df1, df2],ignore_index=True)

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4
5  A5  B5

### Merging Pandas DataFrame

In [81]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                     'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']})
right = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                     'C': ['C0', 'C1', 'C2'],
                     'D': ['D0', 'D1', 'D2']})

In [82]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2

In [83]:
right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2

In [84]:
pd.merge(left, right, how='inner', on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2

### Joining Pandas DataFrame

In [85]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']}, index=['K0', 'K1', 'K2'])
right = pd.DataFrame({'C': ['C0', 'C1', 'C2'],
                     'D': ['D0', 'D1', 'D2']}, index=['K0', 'K2', 'K3'])

In [86]:
left

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [87]:
right

C   D
K0  C0  D0
K2  C1  D1
K3  C2  D2

In [88]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C1   D1

In [92]:
left.join(right, how='right')

A    B   C   D
K0   A0   B0  C0  D0
K2   A2   B2  C1  D1
K3  NaN  NaN  C2  D2

## Pandas DataFrame Built-in MEURods, Attributes, and Compatible Python Function

In [93]:
df = pd.DataFrame({'col1': [1,2,3,4, None],'col2': ['THB', 'EUR', 'THB', 'JPY', 'CAD'], 'col3': [10, 500, 6, 1000, 7]})
df.head()

col1 col2  col3
0   1.0  THB    10
1   2.0  EUR   500
2   3.0  THB     6
3   4.0  JPY  1000
4   NaN  CAD     7

In [94]:
df['col2'].unique()

array(['THB', 'EUR', 'JPY', 'CAD'], dtype=object)

In [95]:
df['col2'].nunique()

4

In [96]:
len('THB')

3

In [97]:
df['col2'].apply(len)

0    3
1    3
2    3
3    3
4    3
Name: col2, dtype: int64

In [98]:
df['col2'].apply(lambda text: text+'XXX')

0    THBXXX
1    EURXXX
2    THBXXX
3    JPYXXX
4    CADXXX
Name: col2, dtype: object

In [99]:
def concat_xxx(text):
    return text+'XXX'
df['col2'].apply(concat_xxx)

0    THBXXX
1    EURXXX
2    THBXXX
3    JPYXXX
4    CADXXX
Name: col2, dtype: object

In [100]:
df['col1'].sum()

10.0

In [101]:
df.sort_values(by='col2')

col1 col2  col3
4   NaN  CAD     7
1   2.0  EUR   500
3   4.0  JPY  1000
0   1.0  THB    10
2   3.0  THB     6

In [102]:
df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4   True  False  False

In [103]:
df = df.dropna()
df

col1 col2  col3
0   1.0  THB    10
1   2.0  EUR   500
2   3.0  THB     6
3   4.0  JPY  1000

In [104]:
df = df.append({'col1':10, 'col2': np.nan, 'col3': 15}, ignore_index=True)

In [105]:
df

col1 col2    col3
0   1.0  THB    10.0
1   2.0  EUR   500.0
2   3.0  THB     6.0
3   4.0  JPY  1000.0
4  10.0  NaN    15.0

In [106]:
df.fillna('GBP')

col1 col2    col3
0   1.0  THB    10.0
1   2.0  EUR   500.0
2   3.0  THB     6.0
3   4.0  JPY  1000.0
4  10.0  GBP    15.0

In [107]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [108]:
df_new = df[(df['col2']=='THB') & (df['col3']>8)]
df_new

col1 col2  col3
0   1.0  THB  10.0

In [109]:
del df['col1']

In [110]:
df

col2    col3
0  THB    10.0
1  EUR   500.0
2  THB     6.0
3  JPY  1000.0
4  NaN    15.0

## Pivoting Pandas DataFrame

In [111]:
data = {'A':['head','head','head','tail','tail','tail'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [112]:
df

A    B  C  D
0  head  one  x  1
1  head  one  y  3
2  head  two  x  2
3  tail  two  y  5
4  tail  one  x  4
5  tail  one  y  1

In [113]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C           x    y
A    B            
head one  1.0  3.0
     two  2.0  NaN
tail one  4.0  1.0
     two  NaN  5.0